namespace Identity.Domain.Enums;
public enum PermissionType
{
    CreateUser = 0,
    ReadUser = 1,
    UpdateUser = 2,
    DeleteUser = 3,
    CreateRole = 10,
    ReadRole = 11,
    UpdateRole = 12,
    DeleteRole = 13,
    CreatePermission = 20,
    ReadPermission = 21,
    UpdatePermission = 22,
    DeletePermission = 23,
    ManagePerson = 30,
    ViewPerson = 31,
    ManageAcademic = 40,
    ViewAcademic = 41,
    ManageVirtualPOS = 50,
    ViewVirtualPOS = 51,
    ProcessPayments = 52,
    ManageWallet = 60,
    ViewWallet = 61,
    TransferFunds = 62,
    ManageAccessControl = 70,
    ViewAccessLogs = 71,
    IssueCards = 72,
    ManagePayroll = 80,
    ViewPayroll = 81,
    ProcessPayroll = 82,
    ViewDashboard = 100,
    ExportData = 101,
    ViewReports = 102,
    ManageSettings = 103
}